NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ulis.vnu.edu.vn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ulis.vnu.edu.vn-cert.pem
    OrganizationalUnitIdentifier: peer
